# Generated by Django 4.2 on 2023-04-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
